stages:
  prepare:
    cmd: /home/alena/Рабочий стол/Уник/наука о данных/dvc/dvc/src/prepare.py
    deps:
    - src/prepare.py
    outs:
    - data

  train:
    cmd: /home/alena/Рабочий стол/Уник/наука о данных/dvc/dvc/src/train.py data
    deps:
    - data
    - src/train.py
    params:
    - train.epochs
metrics:
- plots/metrics.json
